---
# vars file for install-nim

nms_setup_vars: [
  install, uninstall, upgrade,
]

nms_default_setup: install

nms_state_vals:
  install: present
  uninstall: absent
  upgrade: latest

nms_state: "{{ nms_state_vals[nms_setup] | default(nms_state_vals[nms_default_setup]) }}"

nms_debian_signing_key_id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
nms_debian_signing_key_keyring_path: /usr/share/keyrings/nginx-archive-keyring.gpg
nms_debian_signing_key_repo: deb [signed-by={{ nms_debian_signing_key_keyring_path }}] https://pkgs.nginx.com/nms/{{ansible_distribution|lower}} {{ansible_distribution_release}} nginx-plus
nms_debian_apt_config_url: https://cs.nginx.com/static/files/90pkgs-nginx
nms_debian_apt_config_path: /etc/apt/apt.conf.d

nms_services: [
  nms, nms-core, nms-dpm, nms-ingestion
]

# Supported NGINX Open Source distributions
# https://docs.nginx.com/nginx-management-suite/tech-specs/#nginx-management-suite
nms_distributions: [
  Amazon, CentOS, Debian, OracleLinux, RedHat, Ubuntu,
]

nms_redhat7_pip27: https://bootstrap.pypa.io/pip/2.7/get-pip.py

